name: docker-graphql

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: | 
        echo "Iniciando Login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Fin del Login"
        
    - name: Construir imagen
      run: |
        echo "Construyendo la imagen"
        docker build -t rainelu/docker-graphql:0.0.2 .
        docker build -t rainelu/docker-graphql .
        
    - name: Docker Push Image
      run: |
        docker push rainelu/docker-graphql:0.0.2
        docker push rainelu/docker-graphql
      
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
