name: docker-graphql

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-${increment}"
      id: version
      
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: | 
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
    - name: Construir imagen
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        echo "Construyendo la imagen"
        docker build -t rainelu/docker-graphql:$NEW_VERSION .
        docker build -t rainelu/docker-graphql .
        
    - name: Docker Push Image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker push rainelu/docker-graphql:$NEW_VERSION
        docker push rainelu/docker-graphql
